=== udit19281/BTP-KG/Material/Legislation & Metadata for PMLA/Legislation & Metadata for PMLA/Act Sample_DTD and style sheet/Legislation.dtd
<!--

Project: westlaw-india
Module: Legislation.dtd
Description: The Data Delivery DTD for WL India Central Legislation and Bills XML
Version: $Revision: 1.7 $
Author: Indlaw / C051141 - Paul Parkins
Language: DTD
Date started: 27/03/2009
Copyright(c) Thomson Reuters (Legal) Limited 2009
Notes:

Based on Indlaw's existing Legislation.dtd, but with these changes:
* Rearranged a little and added a few comments
* Renamed Date to PublishDate and added CommencementDate for document level dates
* Added commencementDate attribute to Section for provision-level commencement dates
* Added IndlawLeg (duplicated from the Cases DTD for Legislation references inline within fulltext)
* Allow IndlawLeg elements as children of FootNote elements
* Added SubHeading as a possible child of Section for schedule part/paragraph group structure headings (currently plain inline text)
* Added ID attributes for: Legislation, Chapter, Section and IndlawLeg
* Added IndlawLeg as a possible child of Preamble
* Added the sections attribute to Number (see Number's comment)
* Wherever either P or NewPara are valid, allow both
* Sections elements now only contain Section elements, not #PCDATA, FootNoteRef or NewPara elements, and must contain at least one Section
* Changed Forms and Form elements to the a (HTML anchor) element
* Removed FootNotes as a child of Legislation - these document-level footnotes are never used
* Removed unused elements: FootNoteNo, FootNoteRef, FormName, EditHistory, EditorsNote, and their descendents

-->


<!--
	Legislation is the doctype for Central Legislation and Bills.
-->

<!ELEMENT Legislation (Number, Year, LegislativeBody, PublishDate, CommencementDate?, Title, Status?, Preamble, StatementofObject, Chapters, Laws, Industries, States)>
<!ATTLIST Legislation
	id CDATA #REQUIRED
>


<!--
	Legislation metadata elements.
-->

<!ELEMENT Year (#PCDATA)>
<!ELEMENT LegislativeBody (#PCDATA)>
<!ELEMENT PublishDate (#PCDATA)>
<!ELEMENT CommencementDate (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT Status (#PCDATA)>
<!ELEMENT Laws (Law)*>
<!ELEMENT Law (#PCDATA)>
<!ELEMENT Industries (Industry)*>
<!ELEMENT Industry (#PCDATA)>
<!ELEMENT States (State)*>
<!ELEMENT State (#PCDATA)>


<!--
	Number is used for various things, one of which is a Section's number.
	However, this can be a range rather than an individual Section number.
	When it is a range, the	individual Rule numbers within the range are listed
	in the sections attribute, comma-separated, e.g.:
		<Number sections="95,96,97AA,97AB,98ZA,98,99,100,101">95-101</Number>
-->
<!ELEMENT Number (#PCDATA)>
<!ATTLIST Number
	sections CDATA #IMPLIED
>


<!--
	Legislation full text content elements.
-->

<!ELEMENT Preamble (#PCDATA | IndlawLeg | Fn | P | NewPara | FootNotes)*>
<!ELEMENT StatementofObject (#PCDATA | P | NewPara)*>
<!ELEMENT Chapters (Chapter+)>
<!ELEMENT Chapter (Number, Name, Sections)>
<!ATTLIST Chapter
	id CDATA #REQUIRED
>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Sections (Section)+>
<!ELEMENT Section (#PCDATA | Number | Heading | SubHeading | P | NewPara | a | Fn | FootNotes | Table | IndlawLeg)*>
<!ATTLIST Section
	id CDATA #REQUIRED
	commencementDate CDATA #IMPLIED
>
<!ELEMENT Heading (#PCDATA | Fn)*>
<!ELEMENT SubHeading (#PCDATA)>
<!ELEMENT NewPara EMPTY>
<!ELEMENT P EMPTY>


<!--
	PDF reference element. Indlaw editors enter PDF references as HTML a
	elements. There are no other uses of this element other than references to
	PDF	files/BLOBs. This works like any other HTML a element - the text to be
	rendered is the element's content, and the href attribute contains the
	target of the link - the PDF reference in this case.
-->

<!ELEMENT a (#PCDATA)>
<!ATTLIST a
	href CDATA #REQUIRED
>


<!--
	Footnote elements.
-->

<!ELEMENT Fn (#PCDATA)>
<!ELEMENT FootNotes (FootNote)*>
<!ELEMENT FootNote (#PCDATA | P | NewPara | Table | IndlawLeg)*>


<!--
	Table elements.
-->

<!ELEMENT Table (TableHeading?, Trh?, Tr+)>
<!ELEMENT TableHeading (#PCDATA)>
<!ELEMENT Trh (Td+)>
<!ELEMENT Tr (Td+)>
<!ELEMENT Td (#PCDATA | Fn | P | NewPara)*>


<!--
	Citation elements.
	
	For UK IndlawLeg citations, the country attribute is "UK". If not defined,
	the default is Indian Central Legislation - "India".
-->

<!ELEMENT IndlawLeg (OLeg, FLeg)+>
<!ATTLIST IndlawLeg
	id CDATA #REQUIRED
	country CDATA "India"
>
<!ELEMENT OLeg (#PCDATA)>
<!ELEMENT FLeg (#PCDATA)>

=== udit19281/BTP-KG/Material/Legislation & Metadata for PMLA/Legislation & Metadata for PMLA/Act Sample_DTD and style sheet/Legislation (72).xml
<?xml version="1.0" standalone="no"?>
<!-- edited with XML Spy v3.0.7 (http://www.xmlspy.com) by Achal (Icpl) -->
<!DOCTYPE Legislation SYSTEM "../../dtd/Legislation.dtd" [
	<!ENTITY amp "&#38;#38;">
	<!ENTITY apos "&#39;">
]>
<Legislation>
	<Number>25</Number>
	<Year>1993</Year>
	<LegislativeBody>Central Legislature</LegislativeBody>
	<Date>02/04/1993</Date>
	<Title>Gold Bonds (Immunities and Exemptions) Act, 1993</Title>
	<Preamble>An Act to provide for certain immunities to the subscribers of the Gold Bonds and for certain exemptions from direct taxes in relation to such Bonds and for matters connected therewith or incidental thereto.WHEREAS with a view to mobilizing the idle gold resources of residents in India, it is expedient to provide for certain immunities and exemptions to render it possible for such residents to subscribe to Gold Bonds;BE it enacted by Parliament in the Forty-fourth Year of the Republic India as follows:-</Preamble>
	<StatementofObject>It was indicated in the Budget speech for the year 1992-93 that Government will introduce a Gold Bond Scheme to mobilise the idle gold resources of ordinary citizens to supplement official reserves and that the proposed Gold Bonds will not attract income-tax or gift-tax and that the holders of the said Bonds will not be asked any questions about the source of the gold holding.<P/>
		<P/>2. With a view to enabling the Central Government to issue the bonds before the end of the financial year 1992-93, the Gold Bonds (Immunities and Exemptions) Ordinance, 1993, was promulgated by the President on the 31st day of January, 1993. Section 4 of the said Ordinance grants certain immunities to the subscribers to the Gold Bonds under the wealth-tax Act, 1957, the Gift-tax Act, 1958, the Income-tax Act, 1961, the Customs Act, 1962, the Foreign Exchange Regulation Act, 1973, and the Foreign Contribution (Regulation) Act, 1976. By virtue of the said immunities, no subscriber will be required to disclose, for any purpose whatsoever, the nature and source of acquisition of the gold subscribed for the Gold Bonds, including the source of money with which the Gold was acquired. Further, no inquiry or investigation will be commenced against any subscriber under any of the said Acts on the ground that such subscriber owns the Gold Bonds and the fact of ownership of the Gold Bonds will not be taken into account for the purposes of, and will be inadmissible as evidence in, any proceedings under any of the said Acts. However, the said immunities will not be available in relation to any proceedings connected with the Gold subscribed by the subscriber where such proceedings have already been initiated, before the date of promulgation of the Ordinance, in accordance with the provisions of any of the said Acts, Section 5 of the Ordinance provides for certain tax exemptions under the Income-tax Act, 1961 and the Gift-tax Act, 1958.<P/>
		<P/>3. The Bill seeks to replace the above mentioned Ordinance.</StatementofObject>
	<Chapters>
		<Chapter>
			<Number/>
			<Name/>
			<Sections>
				<Section>
					<Number>1</Number>
					<Heading>Short title and commencement</Heading>(1) This Act may be called the Gold Bonds (Immunities and Exemptions) Act, 1993.<NewPara/>2) It shall be deemed to have come into force on the 31st day of January, 1993.<NewPara/>
				</Section>
				<Section>
					<Number>2</Number>
					<Heading>Definitions</Heading>In this Act, unless the context otherwise requires,-<NewPara/>(a) "Gold Bonds" means the Gold Bonds, 1998, issued by the Central Government in accordance with the scheme framed by that Government under section 3;<NewPara/>(b) "subscriber" means an individual, a Hindu undivided family, trustees of a trust, a firm or a company, being a resident or residents in India, who has or have initially subscribed to the Gold Bonds.<NewPara/>Explanation.- For the purposes of this clause, the expression "individual" shall also include,-<NewPara/>(i) his legal heirs; or<NewPara/>(ii) where a partition has taken place among the members of the Hindu undivided family, every member of such family having a share in the Gold Bonds;<NewPara/>(c) all other words and expressions used in this Act but not defined and defined in the Income-tax Act, 1961 shall have the meanings respectively assigned to them in that Act.<NewPara/>
				</Section>
				<Section>
					<Number>3</Number>
					<Heading>Gold Bonds Scheme</Heading>(1) The Central Government may, by notification in the Official Gazette, frame a scheme for subscription to the Gold Bonds, 1998, on or after the date of commencement of this Act, but before the specified date.<NewPara/>Explanation-For the purposes of this sub-section, "specified date" means the 31st day of March, 1993 or such other later date as the Central Government may, by notification in the Official Gazette, specify in this behalf.<NewPara/>(2) The scheme framed under sub-section (1) shall be laid, as soon may be after it is framed, before each House of Parliament.<NewPara/>
				</Section>
				<Section>
					<Number>4</Number>
					<Heading>Immunities</Heading>(1) Notwithstanding anything contained in the Wealth-tax Act, 1957,(27 of 1957.) the Gift-tax Act, 1958,(18 of 1958.) the Income-tax Act, 1961,(43 of 1961) the Customs Act, 1962, (52 of 1962.) the Foreign Exchange Regulation Act, 1973 (46 of 1973.)and the Foreign Contribution (Regulation) Act, 1976 (49 of 1976.) ,-<NewPara/>(a) no subscriber shall be required to disclose, for any purpose whatsoever, the nature and source of acquisition of the gold subscribed for the Gold Bonds, including the source of money with which the gold was acquired;<NewPara/>(b) no inquiry or investigation shall be commenced against any subscriber under any of the said acts on the ground that such subscriber owns the Gold Bonds; and<NewPara/>(c) the fact that any subscriber owns the Gold Bonds shall not be taken into account for the purposes of, and shall be inadmissible as evidence in, any proceedings under any of the said Acts:<NewPara/>Provided that nothing contained in this Sub-section shall apply where any proceedings in respect of the gold subscribed by the subscriber have already been initiated before the commencement of this Act in accordance with the provisions of any of the aforesaid Acts:<NewPara/>(2) Nothing in sub-section (1) shall apply in relation to prosecution for any offence punishable under Chapter IX or Chapter XVII of the Indian Penal Code, (45 of 1860) the Narcotic Drug and Psychotropic Substances Act, 1985,(61 of 1985) the Terrorist and Disruptive Activities (Prevention) Act, 1987,(28 of 1987) the Prevention of Corruption Act, 1988 (49 of 1988) or for the purposes of enforcement of any civil liability.<NewPara/>
				</Section>
				<Section>
					<Number>5</Number>
					<Heading>Gold Bonds not to be taken into account in certain cases</Heading>Without prejudice to the generality of the provisions of section 4,-<NewPara/>(a) the provision of the Income-tax Act, 1961(43 of 1961) shall not apply to-<NewPara/>(i) any interest accruing to the subscriber from the Gold Bonds:<NewPara/>(ii) any long-term capital gains arising to the subscriber:<NewPara/>(b) the provisions of the Gift-tax Act, 1958 (18 of 1958) shall not apply where the gift of the Gold Bonds is made by a subscriber, being an individual, to his spouse, child or parent.<NewPara/>
				</Section>
				<Section>
					<Number>6</Number>
					<Heading>Repeal and savings</Heading>(1) The Gold Bonds (Immunities and Exemptions) Ordinance, 1993 (Ord.22 of 1993.) is hereby repealed.<NewPara/>(2) Notwithstanding such repeal, anything done or any action taken under the said Ordinance, shall be deemed to have been done or taken under the corresponding provisions of this Act.<NewPara/>
				</Section>
			</Sections>
		</Chapter>
	</Chapters>
	<FootNotes/>
	<EditorsNote/>
	<Laws>
		<Law>Banking &amp; Finance</Law>
		<Law>Income Tax &amp; Direct Taxes</Law>
	</Laws>
	<Industries>
		<Industry>Drug</Industry>
	</Industries>
	<States>
		<State>Center</State>
		<State>Others</State>
	</States>
</Legislation>

=== udit19281/BTP-KG/Material/15-3-22/XML of PML Amendment Act (Finance Act, 2019).xml
<?xml version="1.0" standalone="no"?><!-- edited with XML Spy v3.0.7 (http://www.xmlspy.com) by Rajgopal (ICPL) --><!DOCTYPE Legislation SYSTEM "../../dtd/Legislation.dtd" [<!ENTITY amp "&#38;#38;"><!ENTITY apos "&#39;">]><Legislation><Number>23</Number><Year>2019</Year><LegislativeBody>Central Legislature</LegislativeBody><Date>01/08/2019</Date><Title> Finance (No. 2) Act, 2019</Title><Preamble> An Act to give effect to the financial proposals of the Central Government for the financial year 2019-2020.
BE it enacted by Parliament in the Seventieth Year of the Republic of India as follows:-</Preamble>
<StatementofObject></StatementofObject><Chapters><Chapter><Number>CHAPTER I</Number><Name>PRELIMINARY</Name><Sections><Section><Number>1</Number><Heading>Short title, extent and commencement</Heading>(1) This Act may be called the Finance (No. 2) Act, 2019.<NewPara/>((2) Save as otherwise provided in this Act,-<NewPara/>
(a) sections 2 to 69 shall be deemed to have come into force on the 1st day of April, 2019;<NewPara/>
(b) sections 92 to 112 and section 114 shall come into force on such date as the Central Government may, by notification in the Official Gazette, appoint.<NewPara/></Section></Sections>
</Chapter>
<Chapter><Number>PART XIII</Number><Name>AMENDMENTS TO THE PREVENTION OF MONEY-LAUNDERING ACT, 2002</Name><Sections>
<Section><Number>2</Number><Heading> Amendment of section 3</Heading>"Explanation.-For the removal of doubts, it is hereby clarified that,-<NewPara/>
(i) a person shall be guilty of offence of money-laundering if such person is found to have directly or indirectly attempted to indulge or knowingly assisted or knowingly is a party or is actually involved in one or more of the following processes or activities connected with proceeds of crime, namely:-<NewPara/>
(a) concealment; or<NewPara/>
(b) possession; or<NewPara/>
(c) acquisition; or<NewPara/>
(d) use; or<NewPara/>
(e) projecting as untainted property; or<NewPara/>
(f) claiming as untainted property,<NewPara/>
in any manner whatsoever;<NewPara/>
(ii) the process or activity connected with proceeds of crime is a continuing activity and continues till such time a person is directly or indirectly enjoying the proceeds of crime by its concealment or possession or acquisition or use or projecting it as untainted property or claiming it as untainted property in any manner whatsoever.".
<NewPara/></Section></Sections></Chapter></Chapters><FootNotes/><EditorsNote/><Laws><Law>Banking &amp; Finance</Law><Law>RBI</Law></Laws><Industries/><States><State>Center</State></States></Legislation>

=== udit19281/BTP-KG/Material/15-3-22/XML of PML (Amendment) Act, 2012.xml
<?xml version="1.0" standalone="no"?><!-- edited with XML Spy v3.0.7 (http://www.xmlspy.com) by Rajgopal (ICPL) --><!DOCTYPE Legislation SYSTEM "../../dtd/Legislation.dtd" [<!ENTITY amp "&#38;#38;"><!ENTITY apos "&#39;">]><Legislation><Number>2</Number><Year>2013</Year><LegislativeBody>Central Legislature</LegislativeBody><Date>03/01/2013</Date><Title> Prevention of Money-laundering (Amendment) Act, 2012</Title><Preamble> An Act further to amend the Prevention of Money-laundering Act, 2002. Be it enacted by Parliament in the Sixty-third Year of the Republic of India as follows:-</Preamble>
<StatementofObject></StatementofObject><Chapters><Chapter><Number>CHAPTER I</Number><Name>PRELIMINARY</Name><Sections><Section><Number>1</Number><Heading>Short title, extent and commencement</Heading> (1) This Act may be called the Prevention of Money-laundering (Amendment) Act, 2012.<NewPara/>(2) It shall come into force on such date as the Central Government may, by notification in the Official Gazette, appoint and different dates may be appointed for different provisions of this Act.<NewPara/></Section>
<Section><Number>2</Number><Heading>Amendment of Section 3</Heading>In Section 3 of the principle act, for the words "proceeds of crime and projecting", the word "proceeds of crime including its concealment, possession, acquisition or use and projecting or claiming"<NewPara/></Section><Section><Number>3</Number><Heading> Amendment of section 5</Heading>In section 5 of the principal Act, for sub-section (1), the following sub-section shall be substituted, namely:-<NewPara/>"(1) Where the Director or any other officer not below the rank of Deputy Director authorised by the Director for the purposes of this section, has reason to believe (the reason for such belief to be recorded in writing), on the basis of material in his possession, that- <NewPara/>
(a)	any person is in possession of any proceeds of crime; and <NewPara/>(b)	such proceeds of crime are likely to be concealed, transferred or dealt with in any manner which may result in frustrating any proceedings relating to confiscation of such proceeds of crime under this Chapter, <NewPara/>he may, by order in writing, provisionally attach such property for a period not exceeding one hundred and eighty days from the date of the order, in such manner as may be prescribed: <NewPara/>
Provided that no such order of attachment shall be made unless, in relation to the scheduled offence, a report has been forwarded to a Magistrate under section 173 of the Code of Criminal Procedure, 1973, or a complaint has been filed by a person authorised to investigate the offence mentioned in that Schedule, before a Magistrate or court for taking cognizance of the scheduled offence, as the case may be, or a similar report or complaint has been made or filed under the corresponding law of any other country: <NewPara/>Provided further that, notwithstanding anything contained in clause (6), any property of any person may be attached under this section if the Director or any other officer not below the rank of Deputy Director authorised by him for the purposes of this section has reason to believe (the reasons for such belief to be recorded in writing), on the basis of material in his possession, that if such property involved in money- laundering is not attached immediately under this Chapter, the non-attachment of the property is likely to frustrate any proceeding under this Act.".<NewPara/></Section></Sections></Chapter></Chapters><FootNotes/><EditorsNote/><Laws><Law>Banking &amp; Finance</Law><Law>RBI</Law></Laws><Industries/><States><State>Center</State></States></Legislation>
